kind: Namespace
apiVersion: v1
metadata:
  name: django-notes-app
  labels:
    name: django-notes-app
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-app-deployment
  namespace: django-notes-app
  labels:
    app: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      name: notes-app-deployment-pod
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: priyanshuprafful/notes-app-k8sp:latest
        ports:
        - containerPort: 8000